### ISSUE TITLE
Allow Lua to get where damage occurs 

### ISSUE THREAD

**Issue by R00Ki3** [fortressforever/fortressforever#104]
Allow Lua  to get from the damage info where the damage occurred. Being Head, legs, torso, ect.

**Comment by squeek502** [comment]
You could approximate this using damageinfo:GetDamagePosition() and comparing it to the origin of the victim.

**Comment by R00Ki3** [comment]
Ah i see, I really wasn't sure what that function was used for. Thanks Squeek.
