### ISSUE TITLE
creditting kill assists.

### ISSUE THREAD

**Issue by FDA-** [fortressforever/fortressforever#109]
Tired of getting snaked out of my kills when someone is one shot and the scout comes along and just casually pops off a single shotty.

**Comment by squeek502** [comment]
How should they work? Do they earn the assister a frag? How are they shown in deathnotices? Is there a damage dealt threshold for it counting as an assist? Does time since last damage matter?

I don't really know how other games handle this.

**Comment by twincannon** [comment]
In TF2 it's it's pretty simple, in that you just get an assist and however many points per assist (just 1 I think). It's based on who did the most damage in the previous x amount of time. If a medic is healing the person who got the kill, they're given priority over other damage dealers.

The newer Battlefield games do a system where you get +100 for a kill, and then assisting players get points based on the % damage they dealt.

In the Quake 3 mods Rocket Arena and Threewave, each 100 damage is a point, and frags are a point regardless of how much damage you dealt. So if you killed someone with 100/200 full to dead you'd get 4 points total (3 for damage, 1 for frag).

**Comment by FDA-** [comment]
Yeah basically who ever did the most amount of damage in a certain amount of time before the kill gets an assist. Killing blow rewards the kill, and the kill feed would read "FDA + Twincannon ===,=[H] Squeek". That's a rocket launcher. I'd say add a threshold, where you have to do at least 50% to be eligible for an assist. That'd make assists in comp play more meaningful, you'd know when someone actually put damage on something. But it might happen less in the pubs where potentially 4 different people could do 25%

I think assists in TF2 count as half points. It obviously doesn't keep track of halves, with someone having 1.5 kills. But I think if you have 1 kill and 2 assists it shows as 2 points.

**Comment by fpsmoto** [comment]
In addition to that, an Assists column on the Scoreboard would be nice.

**Comment by AfterShockFF** [comment]
What happens if the damage dealt by the previous person is then healed up, then he gets oneshot headshot?

Also do I get an assist if i single shotty someone who then takes a detpack / backstab?

**Comment by FDA-** [comment]
In the event of healing lost health, there's still a lack of armor, meaning the assist still played substantial role in the kill.

Though maybe if the killing blow deals a total of damage greater than the assist dmg and the remaining health, the assist is nulled. As in detpacks, backstabs, and headshots don't really need any "assistance" as you mentioned.

I don't really know though, this is all valid stuff that should be figured out, but I don't think it's at all a detriment to the system. I don't particularly have answers for everything though.

**Comment by WillWowmc** [comment]
As this was added to the game, this should be closed now, right? (Just looking through old issues to find anything I could work on.)

**Comment by squeek502** [comment]
Yep, implemented by #288
