### ISSUE TITLE
Allow SetFriction() to work on players

### ISSUE THREAD

**Issue by R00Ki3** [fortressforever/fortressforever#113]
I'm not sure if this is a bug or what, But SetFriction does nothing for players. It would be nice if it could modify a players friction as well. (Go skating, golfing, and other slippery maps!)

**Comment by squeek502** [comment]
This is a simple fix, but note that with 0 friction you still accelerate at full speed and can get up to crazy speeds insanely quickly. Is that the intended behavior?

**Comment by R00Ki3** [comment]
I was interested in using it to make you slide a far distance. But not infinitely far as it would be with 0 friction.  It was fun testing it with the server cvar but I'd like to apply it to a single player.

**Comment by squeek502** [comment]
Okay, then #116 will do what you want (player:SetFriction(0) will behave exactly like sv_friction 0).
