### ISSUE TITLE
Sound for scout movement weapon

### ISSUE THREAD

**Issue by squeek502** [fortressforever/fortressforever#115]
Needed for #85, probably depends on #114

**Comment by BullyFF** [comment]
FFjumpgun1 added

**Comment by squeek502** [comment]
Nice work, I like that a lot. Note that it might end up having to be shortened, though, but I'm not sure about that yet.

Adding a direct link to it for quick reference in the future: https://soundcloud.com/tudberry/ffjumpgun1?in=tudberry/sets/ffsoundstuff

**Comment by BullyFF** [comment]
File now located at https://soundcloud.com/bullrushband/ffjumpgun1

**Comment by AfterShockFF** [comment]
I've uploaded a tweaked shortened version
