### ISSUE TITLE
Damage indicator flashes duration / intensity should be somewhat related to how much damage you took

### ISSUE THREAD

**Issue by mikeparker** [fortressforever/fortressforever#12]
I'm sure we're not getting a proper circular damage indicator any time soon but this would be an easy first step to giving more useful hit feedback on the HUD.

**Comment by mikeparker** [comment]
Looks like we've actually got some commented out code to do this, to use a longer HUD animation in scripts/HudAnimations.txt. However, it doesn't seem to be working. I'll have to check if the damage is actually coming through in the message.

**Comment by mikeparker** [comment]
I've got this working now: https://github.com/fortressforever/fortressforever/pull/42

**Comment by squeek502** [comment]
Done by #42
