### ISSUE TITLE
ff_dm loading screen and glass

### ISSUE THREAD

**Issue by BullyFF** [fortressforever/fortressforever#135]
Just ran through a few maps on beta and found these issues on ff_dm 

Loading screen 
![2015-03-24_00001](https://cloud.githubusercontent.com/assets/9292586/6794469/f6bc7c4e-d1c9-11e4-9552-75a4a5a74f2a.jpg)
BLUE TEAM v Destroyers is that right ? and FF logo top right is chopped off

Also glass is opaque ? and seems to be fine on other maps
![2015-03-24_00002](https://cloud.githubusercontent.com/assets/9292586/6794481/280c0558-d1ca-11e4-8193-8ff926480cd9.jpg)

**Comment by squeek502** [comment]
Strange. Will need to figure out what material that glass is using and make sure it's included in the Steam version.

**Comment by alaswell** [comment]
models/props/ff_avanti/pole1_glass 

it actually looks like removing the transparency was intentional.

from the .vmf:
//  translucent was causing z-sorting problems with sprites, so away it goes
//  "$translucent" 1

**Comment by alaswell** [comment]
> and FF logo top right is chopped off

that's actually FF wide, so I made it it's own issue #138

Everything else has been fixed!
