### ISSUE TITLE
3rd person RPG should point at where the rocket will go

### ISSUE THREAD

**Issue by AfterShockFF** [fortressforever/fortressforever#146]
In TFC and TF2 the RPG points exactly where the soldier is aiming so its easier to predict and juke their rockets. Most weapons dont matter so much but the RPG is probably the most important there i think.

Will require anim / pose tweaks I guess.

**Comment by squeek502** [comment]
I think Crazycarl actually did this but it never made it into release because it was coupled with some other unfinished animation tweaks. Still need to do some more investigation of the models repo and git a public repo setup.

**Comment by AfterShockFF** [comment]
I messaged carl, he replied: 

I did tweak this, as well as a few other things, in my last commit to the models SVN but I don't know if it ever made it to release. If you run models/trunk/player/ff_player_shared/compile/ff_anim_pF.qc through studiomdl, it should build your animation .mdl. The revision in question was 13671.

**Comment by AfterShockFF** [comment]
Think this is done now
