### ISSUE TITLE
Ask valve to reinstate the linux 2006 srcds.so

### ISSUE THREAD

**Issue by mikeparker** [fortressforever/fortressforever#17]
So we can compile under linux.

EDIT by squeek: Reopen #16 if this ever gets resolved

**Comment by mikeparker** [comment]
squeek: its even listed as a bug on the valve wiki: https://developer.valvesoftware.com/wiki/Steam_Application_IDs#Server_Files - see appid 205

**Comment by squeek502** [comment]
To clarify, this isn't needed to compile under Linux, but instead is needed to _use_ the Linux FF server binary to run a server.

**Comment by DexterHaslem** [comment]
the build process actually looks for some of the other .so in the same appid im quite certain!

**Comment by DexterHaslem** [comment]
yep the following are required before it even tries to build:
srcds/bin/tier0_i486.so
srcds/bin/vstdlib_i486.so

@mikeparker what i said about it building and failing to link if they're missing wasn't true. They have to be present before it even starts building as the makefilecreator itself needs em too

**Comment by squeek502** [comment]
Related issue: https://github.com/ValveSoftware/Source-1-Games/issues/1614

**Comment by illwieckz** [comment]
Hi, I just want to say that the issue is not fixed at all.

There was two problems:
- it was not possible to build some things on GNU/Linux  
  (seems fixed)
- it is not possible to run the server on GNU/Linux because the binaries are not available  
  (not fixed at all)

Binary files like these ones:

```
srcds/srcds_i486
srcds/bin/datacache_i486.so
srcds/bin/dedicated_i486.so
srcds/bin/engine_i486.so
srcds/bin/tier0_i486.so
srcds/bin/unitlib_i486.so
srcds/bin/vphysics_i486.so
srcds/bin/vstdlib_i486.so
```

and _many_ others are still missing.

These files are not distributed at all by SteamCMD.

**Comment by illwieckz** [comment]
Hum, sorry for the noise, following links from issues to issues I did not noticed that I had left the Valve's tracker and this one is not a tracker from Valve.

**Comment by DexterHaslem** [comment]
Well, I don't think valve will distribute them for ep1 again. If you hear otherwise definitely ping this issue again!

**Comment by illwieckz** [comment]
Perhaps it may interest you: https://github.com/ValveSoftware/Source-1-Games/issues/1614#issuecomment-110952718

**Comment by DexterHaslem** [comment]
I also tried old linux binaries and experienced the same crashes you outlined, interesting information regarding faking cpu ids, thanks
