### ISSUE TITLE
Spy weapon visual bug

### ISSUE THREAD

**Issue by R00Ki3** [fortressforever/fortressforever#178]
While holding a gun in a slot that the disguised class doesn't have, it will show the spy's original weapon instead of something the class should be holding. It only happens on classes that recently had some weapons removed.

![2015-03-30_00001](https://cloud.githubusercontent.com/assets/3948413/6904628/e0d40672-d6e7-11e4-801c-8bb80dd2ae4f.jpg)

**Comment by squeek502** [comment]
Haha that's really weird. Will take a look.

**Comment by Xylemon** [comment]
I noticed something today related to this, I saw an enemy Spy disguised as HWGuy, and he was holding out a crowbar with the spy knife animation.
