### ISSUE TITLE
Convert Lua HUD identifiers to a byte when sending over the network

### ISSUE THREAD

**Issue by squeek502** [fortressforever/fortressforever#18]
Something that has been discussed elsewhere.

See: https://github.com/fortressforever/fortressforever/blob/beta/game_shared/ff/ff_utils.cpp#L831

No reason to send the entire string; the client has no use for it other than to identify which HUD element to update. A byte is sufficient because there is already a [hard limit defined of 128 HUD elements](https://github.com/fortressforever/fortressforever/blob/beta/cl_dll/ff/ff_hud_lua.h#L32).

**Comment by AfterShockFF** [comment]
An easy different thing to do would be to reduce all the identifier calls down to 1 character strings. We could easily have a lookup to convert between the long hud identifier names and short 1 character identifiers, in lua. This wouldnt require any code changes, but i'm not too good with lua so i dont know the exact syntax to use for this.

**Comment by AfterShockFF** [comment]
Looks like other lua calls could be improved too, such as FF_LuaHudTimer, AddHudTextToAll

**Comment by AfterShockFF** [comment]
Squeek and I have been playing. see https://github.com/fortressforever/fortressforever/pull/123
