### ISSUE TITLE
Dynamic gib threshold.

### ISSUE THREAD

**Issue by FDA-** [fortressforever/fortressforever#184]
As we all know, the biggest issue with FF has always been about how cool gibs look. As it stands at the current threshold, a player at 1 health can be gibbed by the SSG, yet so many explosives rarely gib still. I think the whole 1hp shotgun gib is neat and all, but to change the threshold any further would make even more shotgun gibs which would just start getting goofy.

So maybe we could have different thresholds for different weapons? I'd honestly like to see explosives gib a lot more often, 50% of the time if not more. The occasional ragdoll is cool, but bathing among the innards of your enemy is waaay more cool.

**Comment by squeek502** [comment]
Relevant code for future reference:
- https://github.com/fortressforever/fortressforever/blob/7568ea46299aa0d934ef846ce44713b4346994d2/dlls/ff/ff_player.cpp#L5853

**Comment by AfterShockFF** [comment]
I think this is a really good idea. We can probably do something really simple like 

https://github.com/fortressforever/fortressforever/blob/7568ea46299aa0d934ef846ce44713b4346994d2/dlls/ff/ff_player.cpp#L5752

```
if (info.GetDamageType() & DMG_BLAST)
    return (GetHealth() <= -FFDEV_GIBDAMAGE_EXPLOSION);

return (GetHealth() <= -FFDEV_GIBDAMAGE);
```
