### ISSUE TITLE
What in the absolute world is going on with our explosion code?

### ISSUE THREAD

**Issue by squeek502** [fortressforever/fortressforever#188]
What is this?
- https://github.com/fortressforever/fortressforever/blob/246e629aa25c9b2e497b45a46093419757a32e75/game_shared/ff/ff_gamerules.cpp#L1327-L1385

Is that still necessary? The last time it had any real changes was 2006.

It also uses 36 as 'half the model height' without checking if the player is crouched. That seems wrong. (EDIT: Should be fixed by #191)

For reference:
- Default HL2 RadiusDamage: https://github.com/fortressforever/fortressforever/blob/beta/game_shared/gamerules.cpp#L463-L470
- Default HL1 RadiusDamage: https://github.com/ValveSoftware/halflife/blob/5c1e1d63eb5a9cb97b3b19f992d4e62aaae02cf0/dmc/dlls/combat.cpp#L886-L958

**Comment by DexterHaslem** [comment]
closing old issue that was cleaned up in PR
