### ISSUE TITLE
Add in-game on-screen keyboard functionality

### ISSUE THREAD

**Issue by squeek502** [fortressforever/fortressforever#201]
Should have a client cvar for self and a client cvar for first/third person spectating. Only really needs to show arrow keys + jump, but maybe also crouch/fire.

Something I've wanted to do for a _long_ time.

**Comment by fpsmoto** [comment]
I'd also add grenade buttons to teach people timing.

**Comment by squeek502** [comment]
I think that would be better taken care of by making gren timers visible (and perhaps audible) while spectating.

**Comment by squeek502** [comment]
Progress:

![keystate1](https://cloud.githubusercontent.com/assets/2389051/7127781/ea5c8644-e1fd-11e4-8315-9fe6b8b21ff8.jpg)

**Comment by alaswell** [comment]
Awesome!!! I was just talking to oats about how we needed to make this happen like 3 days ago!

**Comment by AfterShockFF** [comment]
v minor point. You can actually bind arrow keys to turning left/right, so those icons might be confusing to 0.001% of players.
