### ISSUE TITLE
Grenades disappear after falling too far

### ISSUE THREAD

**Issue by squeek502** [fortressforever/fortressforever#22]
From http://forums.fortress-forever.com/project.php?issueid=400

> Old bug, remember it existing way back when I just started playing ff. Usually happens when you throw a conc downwards from high altitudes. Fix plz?

Video demonstration: https://www.youtube.com/watch?v=QJixt671vA8

**Comment by hlstriker** [comment]
I remember this video lol. Anyway, if it's anything like TFC the concs disappear after leaving the world bounds or going over 2000 velocity. A quick check shows it's the same in FF.

We could fix this by capping grenades velocity at 1999 or simply modifying `IsInWorld()` of `BaseEntity.cpp`.

**Comment by squeek502** [comment]
Any idea if there's a reason for the velocity limit?

**Comment by hlstriker** [comment]
I'm honestly not too sure as I've wondered that myself. I couldn't see what it would possibly help when the out of world bounds check is there.

**Comment by squeek502** [comment]
Going to try overriding IsInWorld in CFFProjectileBase and removing the speed check.
