### ISSUE TITLE
Fix cl_spawnweapon_spy tranq

### ISSUE THREAD

**Issue by AfterShockFF** [fortressforever/fortressforever#222]
http://forums.fortress-forever.com/showthread.php?p=508706

When you specify a spawn weapon which is different from the default spawn weapon and happens to be the last weapon you are given on spawn, the code fails at switching to it (as you are already holding it) and then equips your default weapon instead.

The following also dont work for the same reason
cl_spawnweapon_scout nailgun

**Comment by AfterShockFF** [comment]
Code that breaks is here in ff_player.cpp

```
    CBaseCombatWeapon *pSpawnWeapon = Weapon_OwnsThisType(weaponSpawn);
    if(pSpawnWpn && pSpawnWeapon)
    {
        if(Weapon_Switch(pSpawnWeapon)) // this will be false because you can't switch to a weapon you're already holding, and won't break out
            break;
    }

    pSpawnWeapon = Weapon_OwnsThisType(weaponDefault);
    if(pDefaultWpn && pSpawnWeapon)
    {
        if(Weapon_Switch(pSpawnWeapon))
            break;
    }
```

**Comment by fpsmoto** [comment]
Is this also an issue for the class cfg files with the ffc_spawnslot cvar? I can't seem to get them to work for any class.

**Comment by squeek502** [comment]
What is ffc_spawnslot? Searching 'spawnslot' in this repo turns up no results.

**Comment by fpsmoto** [comment]
I got it from the FF wiki page here:
http://www.fortress-forever.com/wiki/index.php?title=Category:Cvars

**Comment by squeek502** [comment]
Yeah, almost all the info on that page is incorrect (if you check the history, it hasn't been meaningfully updated since July 2006). ffc_ cvars don't exist.

**Comment by AfterShockFF** [comment]
A few options here:
- Get Weapon_Switch to return `true` if you are already holding the weapon (I think I looked into this and it would have knock on effects elsewhere)
- Add an extra clause to say if you are already holding the weapon then don't do anything and break out anyway

Probably the 2nd is better
