### ISSUE TITLE
Jump Pad + Conc should allow for same speed as conc

### ISSUE THREAD

**Issue by fpsmoto** [fortressforever/fortressforever#232]
Right now if you use a jump pad + a conc, you go slower than you would have if you had just used a conc by itself. If using both together, you should be able to travel at the same speed as a conc would take you.

**Comment by squeek502** [comment]
Concs don't have a set speed they give you. The speed after a conc is based on your speed before it goes off (hence why scouts get more speed from concs than medics).

**Comment by FDA-** [comment]
A conc plus jump pad has ALWAYS been slower than just a conc alone. A conc alone has always taken you farther distances at higher speeds. So why not just avoid the jpad if you're going to conc?

**Comment by fpsmoto** [comment]
Wouldn't it make more sense if it were based on the faster of the two speeds? It feels like a penalty for using both together considering I could have used a conc by itself to gain the faster speed. I'm just pointing out how it doesn't make much sense as it works right now. Sure in most cases you can avoid the jump pad but in situations where you can't or accidentally use it, I feel it should go with the speed of the conc if that speed is higher than the jump pad speed.

**Comment by CodeToWin** [comment]
I concur with Moto

**Comment by squeek502** [comment]
There's no way to determine "the speed of the conc" because that'd require knowing the speed at which you _would_ have traveled if you had conced from the ground, which depends on both your horizontal speed when you jump and the timing between when you jump and when the conc explodes (that is, jump timing determines your vertical speed).

So, again, there is no "conc speed."

**Comment by squeek502** [comment]
Another thing: making a jump pad + conc give you the same boost as a conc would reinstate one of the reasons for the jump pad change in the first place:

> It allows for near complete consistency in runs that would otherwise be somewhat difficult/special (for example, rampsliding the FD lip on schtop/monkey)

See #30

**Comment by AfterShockFF** [comment]
Closing - this is a deliberate decision to ensure depth of choice between a consistent but slower conc using the jumppad vs a riskier but stronger conc via handheld.
