### ISSUE TITLE
scout can't spawn with crowbar

### ISSUE THREAD

**Issue by 9u-9u-9u** [fortressforever/fortressforever#233]
the script:

cl_spawnweapon_scout "crowbar"

doesn't work in scout.cfg I still spawn with shottie (it shouldn't be related to the similar spy's bug of not being able to spawn with tranq) 

the script works in userconfig (only the first time spawning though ofc)

**Comment by squeek502** [comment]
Make sure you don't have cl_spawnweapon_scout set to "shotgun" in another config. You shouldn't need to set the cvar every time you spawn, just once, so whatever it's set to when you spawn should be what you spawn with. If you have cl_spawnweapon_scout "crowbar" in your scout.cfg, it might be executing too late to have any effect, and then some other config might be resetting it to "shotgun" or something.

Or it could be broken still. I ain't know. I really thought we fixed this, though.

Try to reproduce it in a clean environment: 
- Temporarily clear or rename `scout.cfg` and any other config that might autoexec on spawn
- `cl_spawnweapon_scout "crowbar"` in console
- `kill` in console
- See what weapon you spawn with

**Comment by 9u-9u-9u** [comment]
i typed
cl_spawnweapon_scout "crowbar"
in console after renaming scout.cfg and it worked next time i spawned it was with crowbar

this is odd.. after renaming autoexec and userconfig, testing, and then naming them right again, the script now works.. i don't understand why, but the script is working now.. thanks

**Comment by squeek502** [comment]
As a rule of thumb, don't put cl_spawnweapon_ cvars in class cfgs. All cl_spawnweapon_ settings should go in your main config.cfg, because they only need to be set once.
