### ISSUE TITLE
Handheld grenades sometimes don't hurt nearby players

### ISSUE THREAD

**Issue by squeek502** [fortressforever/fortressforever#24]
Somewhat sporadic but semi-reproducable by standing completely still and hand-helding a frag grenade with a player next to you. No clue what would be causing it.

**Comment by hlstriker** [comment]
Does this only happen with frag grenades?

**Comment by squeek502** [comment]
Probably not. Pretty sure I've seen it happen with MIRVs as well (though it's rarer to HH a MIRV).

**Comment by hlstriker** [comment]
I can't check right now so just leaving this thought here. It might be doing a trace that's getting caught between the grenade and the grenades owner (or something else).

**Comment by squeek502** [comment]
Yeah, it's got to be something like that. It seems like it might be specific to a grenade exploding exactly at a player's origin.
