### ISSUE TITLE
Update or remove hints

### ISSUE THREAD

**Issue by AfterShockFF** [fortressforever/fortressforever#250]
We probably have lots of hints that are outdated now, such as mentions of scout caltrops, nail grenades etc.

**Comment by squeek502** [comment]
The state of this is actually not too bad. NeoNL also gave us a set of updated hints a while back on the beta forums that I'm not sure we ever did anything with:

http://forums.fortress-forever.com/showthread.php?t=23242

**Comment by doublah** [comment]
Can this be closed? (From #285)
