### ISSUE TITLE
weird positioning w/ hud_centerid 1

### ISSUE THREAD

**Issue by fryl0ch** [fortressforever/fortressforever#252]
it looks like the hud_centerid 1 positioning code is [doing some wierd stuff with aspect-ratio scaling](https://github.com/fortressforever/fortressforever/blob/v2.46.1/cl_dll/ff/ff_hud_crosshairinfo.cpp#L592-594)

It looks centered in [4:3](http://i.imgur.com/c6e99U9.jpg), slightly off-center in [16:9](http://i.imgur.com/tB7Ro2t.jpg)... and on my setup [(48:9) the issue is a bit exaggerated](http://i.imgur.com/YjtejF3.png)

[imgur album](http://imgur.com/a/LuXqU)

**Comment by fryl0ch** [comment]
looks fine in 16:9, 
![20160519192829_1](https://cloud.githubusercontent.com/assets/7390162/15412737/fa5cd788-1df7-11e6-9b5e-f43cd550c98d.jpg)

however, now in widescreen i'm not seeing anything
![20160519191308_1](https://cloud.githubusercontent.com/assets/7390162/15412756/2f8aca5a-1df8-11e6-9cea-713bfc126030.jpg)

Just got the build going, ill see what i can do with it

**Comment by squeek502** [comment]
Interesting. I'd be curious to know what `surface()->GetScreenSize()` gives for your resolution. If you are comfortable with Visual Studio, set a breakpoint [here](https://github.com/fortressforever/fortressforever/blob/beta/cl_dll/ff/ff_hud_crosshairinfo.cpp#L586) (see [the readme for how to start a debugging session](https://github.com/fortressforever/fortressforever#debugging-an-active-session)) and see what `iScreenWide` and `iScreenTall` get set to.

The only real difference between this and what the crosshair is doing to set its position is that the crosshair uses `ScreenWidth()` while crosshairinfo is using `surface->GetScreenSize()`. I wonder if that's an issue.

**Comment by fryl0ch** [comment]
![untitled-1 copy](https://cloud.githubusercontent.com/assets/7390162/15415405/706a8124-1e10-11e6-9b18-5f5627477fc3.jpg)

i think you might be on to something

**Comment by squeek502** [comment]
Nice, appreciate you looking into this. The difference between `ScreenWidth()` and `surface()->GetScreenSize()` is that `ScreenWidth` gets the root panel size when it can (`ScreenWidth` calls `GetHudSize`):

```
void GetHudSize( int& w, int &h )
{
    vgui::surface()->GetScreenSize( w, h );

    VPANEL hudParent = enginevgui->GetPanel( PANEL_CLIENTDLL );
    if ( hudParent )
    {
        vgui::ipanel()->GetSize( hudParent, w, h );
    }
}
```

I'll fix crosshairinfo and any other instance of `surface()->GetScreenSize()`

**Comment by squeek502** [comment]
Oh, wait, I might have jumped the gun on this actually. The debug screenshot you posted might be before `surface()->GetScreenSize()` has been called which means `iScreenWide` has an arbitrary value. You'd need to either set a breakpoint after the line with `surface()->GetScreenSize()` or step over that line (F10) to make sure iScreenWide is populated with the correct value.

**Comment by fryl0ch** [comment]
> The debug screenshot you posted might be before surface()->GetScreenSize() has been called

derp, you're right of course; haven't c'd in a while =\
here's a (hopefully) more useful trace

![ff_debug](https://cloud.githubusercontent.com/assets/7390162/15448916/f612b04e-1f3c-11e6-9112-deb2a23c9c4f.gif)

**Comment by fryl0ch** [comment]
this may not be related, but after i detached i saw this in the ff console

`hit surface has no samples`

**Comment by squeek502** [comment]
Hm, m_flYOffset ending up as 15 after 277.777 is passed to `scheme()->GetProportionalScaledValue()` is really bizzare; the return should be larger than the input. When I step through on 1920x1080 res, an input of 277.777 gets (correctly) scaled to 623.

Maybe the 75 offset should just be scaled manually if `GetProportionalScaledValue` is acting up on very high resolutions.

**Comment by squeek502** [comment]
Haha, I'm actually just a dummy. All of this proportional scaling has actually never done anything. It's scaling down and then up using the same ratio, resulting in (what should be) the same value anyway. Like so:

```
int value = 100;
float scale = 0.5;
float normalizedValue = value * scale;
float proportionalValue = value / scale;
// proportionalValue == value
```

The 75 offset has always been constant on all resolutions, so I guess I'll just keep it that way.

**Comment by squeek502** [comment]
Alright, @fryl0ch, if you could test these changes: https://github.com/fortressforever/fortressforever/commit/7e5264898b1bf1aa122edc923ad7e09c60ab5e99 and let me know if crosshair info shows up for you, it'd be much appreciated.

**Comment by fryl0ch** [comment]
sorry i dropped the ball on this (it's only been 8 years, talk about a necro post...) just reinstalled, running 5120x1440 these days, if you're bored and interested in revisiting this lmk
