### ISSUE TITLE
Broken spectator first-person conc effects

### ISSUE THREAD

**Issue by doublah** [fortressforever/fortressforever#284]
Viewmodel still moves after the player being spectated caps/respawns while conced when viewed in spectator (Crosshair does show, however).

**Comment by squeek502** [comment]
Relevant code (I would assume):

https://github.com/fortressforever/fortressforever/blob/beta/cl_dll/ff/c_ff_player.cpp#L2265-L2308

**Comment by AfterShockFF** [comment]
There appears to be a small amount of facepalm here too https://github.com/fortressforever/fortressforever/blob/beta/dlls/ff/ff_player.cpp#L5946-5954
