### ISSUE TITLE
Default hud_deathnotice_highlightself to 1

### ISSUE THREAD

**Issue by doublah** [fortressforever/fortressforever#293]
Would be a lot more useful for newbies imo.

**Comment by FDA-** [comment]
+1

**Comment by squeek502** [comment]
Yeah, I quite like this option. I think it could do with some improvements as well (add a border, and make the border/background color customizable). I think CS:GO's is really nice, for example:

![](https://i.ytimg.com/vi/GREqXtPybeI/maxresdefault.jpg)
