### ISSUE TITLE
Steam Betas for major balance updates

### ISSUE THREAD

**Issue by doublah** [fortressforever/fortressforever#294]
Add Steam betas for public testing of balance updates.

**Comment by squeek502** [comment]
This is actually slighter harder than it might seem:
- We'd need servers that run the beta version. This isn't a huge problem, but it might be something of a roadblock
- We'd need players to switch to the beta branch, which might really mess with custom HUDs/models/sounds/materials/etc. In more recent version of the engines, customs are stored in a separate folder and would be unaffected, but that isn't quite possible for us, so switching branches will likely override all customs each time (see https://github.com/fortressforever/fortressforever/issues/95)

It's certainly something that'd be nice to have, though.

**Comment by doublah** [comment]
As for servers, a server would only be needed when there are enough players around to test, and so few (if any) servers would need to run the beta 24/7.

As for that other reason, that's just yet another reason we need to move to Source 2007.

**Comment by DexterHaslem** [comment]
unfortunately for a few reasons moving to source 2007 is not trivial or as easy as it should be

**Comment by doublah** [comment]
Wouldn't it be a lot easier than moving to source 2013? And it does provide a lot benefits like proper steam intergration etc.

**Comment by DexterHaslem** [comment]
not really, 2007 changed both the physical structure and the api layout of the code quite a bit and that is the majority of the effort. 2013 built on that, so they both would need that big lump of effort.

Realistically, while updating to 2013 would be nice, the demand just isnt there (ignoring the development effort isnt either :smile:)
