### ISSUE TITLE
Jump Gun ammo issues

### ISSUE THREAD

**Issue by doublah** [fortressforever/fortressforever#300]
Currently, jump gun has some ammo-related issues:
It uses ammo, giving it limited use.
It shows ammo/ammo type to the user (this should be removed like with melee weapons).
It shares ammo type with nailgun (currently if you use all your nailgun ammo, you cannot use the jump gun, and vice versa).

**Comment by AfterShockFF** [comment]
I agree with all this - thanks for opening.
