### ISSUE TITLE
Changing resolution causes crashes upon joining/creating a server

### ISSUE THREAD

**Issue by AshMarks** [fortressforever/fortressforever#304]
If you change your resolutions while on the main menu, then try to join or create a server, the game will crash with an alert box saying "hl2.exe has stopped working". This is true for both full screen and windowed mode. When you relaunching the game, the issue goes away. If however you change resolutions again, the issue persists.

**Comment by ax-rwnd** [comment]
I can confirm this issue under debian 8 (unstable)/wine 1.8.2 and the latest released steam version (2.6?). The game crashes with a page fault when reading 0x00000024, so my first guess is a bad pointer access.

For me, the issue also appears when resizing from the main menu _after a game has been ended_, but then the crash is immediate. Does this happen to you too, @AshMarks ?

**Comment by doublah** [comment]
Fairly certain this is an engine bug.

**Comment by AshMarks** [comment]
@ax-rwnd Yes, if I enter a server then disconnect then change my resolution the game also crashes. I'm running Windows 10.

**Comment by DexterHaslem** [comment]
Unfortunately this is an engine bug that we cannot fix, so closing for now
