### ISSUE TITLE
Refill jetpack fuel on flag cap/impulse 101

### ISSUE THREAD

**Issue by doublah** [fortressforever/fortressforever#324]

**Comment by squeek502** [comment]
Jetpack fuel doesn't use the ammo system, so this would involve:
- Setting fuel amount to full in CFFPlayer::CheatImpulseCommands
- Exposing player:GetJetpackFuel/player:SetJetpackFuel functions to Lua and calling them in the relevant base_cap functions

**Comment by AfterShockFF** [comment]
Should probably reset overpressure and stuff too. Maybe some 'Restock' command or smoething?

**Comment by DexterHaslem** [comment]
was added in 2.7.6
