### ISSUE TITLE
Sabotaging spy (and their team) can damage own sabotaged SG if friendly fire is off

### ISSUE THREAD

**Issue by doublah** [fortressforever/fortressforever#327]

**Comment by squeek502** [comment]
You mean before it's activated or after?

**Comment by doublah** [comment]
After, and I mean with your normal weapons/grenades, not det. It's possible with friendly fire on.

**Comment by squeek502** [comment]
Strange, wonder if this was accidentally introduced recently. Seems like it worked like this in the past.
