### ISSUE TITLE
Will the mod ever update to the newer SDK, at least Source SDK 2007?

### ISSUE THREAD

**Issue by ArtyIF** [fortressforever/fortressforever#331]
Because the graphics isn't very nice nowadays and it looks like Source SDK 2006 is deprecated now. Like, it's still available, but not recommended. I'd be very happy to see better graphics.

P. S. How can I get started with Omni-Bots? I haven't found the libraries on Omni-Bot site nor in game.

**Comment by squeek502** [comment]
Extremely unlikely at this point. We started a [port to the 2013 SDK but didn't get very far](https://github.com/fortressforever/fortressforever-2013/).

Omni-Bot integration was never really fully finished.

**Comment by WillWowmc** [comment]
Just a note, using a newer engine version won't magically make the graphics much better, if at all. The main change would maybe be lighting, though at this point FF doesn't really neeeeed that. (Besides, graphics wise, Source 2006 is the only source engine version that has a downloadable shader for parallax occlusion mapping, which is something that I like being able to use!)
