### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by tarik02** [fortressforever/fortressforever#337]
Will Fortress Forever support Linux OS?

**Comment by ax-rwnd** [comment]
Having played ff on linux more than on any other platform, wine works absolutely alright for me, save the steam friends integration which makes it crash at startup. I doubt that we'll ever have "real" linux support, given that source2k6 itself has lost support.

If you install steam on wine (follow any of the tutorials available) you should be able to install fortress forever without a hitch, then disable the steam friends integration, boot up and configure to your liking.

**Comment by tarik02** [comment]
@ax-rwnd, oh... sad.

**Comment by DexterHaslem** [comment]
closing per above. Heck, valve puts zero effort into any of their SDKs, RIP
