### ISSUE TITLE
Make assists for suicides count as kill for assister

### ISSUE THREAD

**Issue by doublah** [fortressforever/fortressforever#340]

**Comment by WillWowmc** [comment]
What, like the 'finished off' kinda thing in TF2?

**Comment by doublah** [comment]
Yeah I guess.

**Comment by MaxRideWizardLord** [comment]
So much yes. Finally would punish noobsoldiers who just shoot rockets at wall at point blank just to get an instant refill after killing single medic. Would also make deathmatch\duel\mulch gamemode far more fair. I'd say the time limit should be minimum of about 7 seconds or so between the moment you last time done damage to the enemy and the enemy commit seppuku for the "assists for suicides" feature to work.

**Comment by Jitterskull** [comment]
The thing that trully bothers me is why it hasn't been introduced in the game since the very beginning of it's release.

By the way, it would work just like medkit infection. Once you infect enemy player, no matter how he manages to kill himself, the killfeed still display that you killed the player and you get a very well deserved +1 to frags. I'm surprised why afterburn doesn't have same thing, nor tranqualized enemies; but it should be added to every single weapon, even if it doesn't have special effect on enemy after hitting him.

**Comment by squeek502** [comment]
Any idea for how this should be shown in the death notices? I can't really think of a good way to show it. Would it be acceptable to just give the assister an assist + fortress points and just have it show up as a normal suicide in the death notices?

**Comment by Jitterskull** [comment]
> Any idea for how this should be shown in the death notices? I can't really think of a good way to show it. Would it be acceptable to just give the assister an assist + fortress points and just have it show up as a normal suicide in the death notices?

Death icon is not that necessary, but I guess when player1 damage player2 and soon player2 suicide, it could look like - player1 [deathbones] player2, NOT just a normal [deathbones] player2. The timer before kill assist is gone should be around 10 second or more imho. It would count as a frag, so +1 to kill count and +100 Fortress Forever points. I hope such frag could count in deathmatch gamemode.

**Comment by doublah** [comment]
In my opinion it should be credited as a full kill to the assister, and as a death like normal to the player who dies, it kind of feels like it would be cheating players out of kills otherwise. Also worth considering edge cases, like how does this deal with team damage, should the assister be 'awarded' -1 kill for killing a teammate like a normal teamkill? Does it currently apply to multi-team assists?

Maybe also a self-inflicted kill (whether assisted by others or not) should remove equivalent fortress points for humiliation, but that's probably a seperate suggestion to make.
