### ISSUE TITLE
Training's flamethrower section is outdated

### ISSUE THREAD

**Issue by doublah** [fortressforever/fortressforever#345]
Voice/text instructions have not been changed since pyro's jetpack has been reworked.

**Comment by BullyFF** [comment]
If a lead Dev provides me with a script i can work on this asap.

**Comment by squeek502** [comment]
**training.a_ft01**

> You have been switched to pyro and are now going to learn how to use the jetpack. Holding the special ability key while in the air will activate the jetpack. Run forward, jump, and use the jetpack to get across the gap.

**training.a_ft02**

> Jump and use the jetpack to get across the gap

**training.a_ft_timeout**

> The pyro's special ability is a jetpack. Run forward, jump, and use the jetpack to get across the gap.

I'm really unsure about the phrase 'special ability key', but I really don't know what that should be called. In config terms, it'd be called attack2, but that seems like it might be strange/confusing to call it that. If anyone has a better idea of what that key should be called, that'd be great.

---

<details>
 <summary>Old script (for reference)</summary>

**training.a_ft01**

> You have been switched to pyro and have been given a flamethrower. The flamethrower can be used as a weak jetpack. Point it down, run forward, jump, and shoot the flamethrower to get across the gap.

**training.a_ft02**

> Jump and shoot the flame-thrower while looking down to get across the gap

**training.a_ft_timeout**

> The flamethrower can be used as a weak jetpack. Point it down, run forward, jump, and shoot the flamethrower to get across the gap.

</details>

**Comment by doublah** [comment]
Maybe secondary attack instead of special ability?

**Comment by squeek502** [comment]
The in-game key binding screen says "Secondary / special attack", so something like that would probably make sense.
