### ISSUE TITLE
hl2.exe is still alive after quitting game

### ISSUE THREAD

**Issue by doublah** [fortressforever/fortressforever#351]

**Comment by squeek502** [comment]
Yeah, I get the same thing. Perhaps related to the discord stuff? @DexterHaslem?

**Comment by DexterHaslem** [comment]
Very likely, will look into asap

**Comment by doublah** [comment]
'quit' in console seems to work for me atleast, here's a modified gamemenu to use it, however it is just a workaround.

https://github.com/doublah/fortressforever-scripts/commit/1b25999b973378c4bb5da23aa6877f05ca30a74f

**Comment by DexterHaslem** [comment]
I can't reproduce reliably, but can tell something is up with the discord stuff. it does not cleanly exit sometimes, maybe causing the process to hang for others. 

I can effectively turn it off by deleting `discord-rpc.dll` and pushing an update until figuring out root cause. that sound good @squeek502 ? discord rich integration doesnt really bring much to the table for us anyway

**Comment by Jitterskull** [comment]
I've been having this issue since somewhere... 2017, for sure. I don't know when discord was added to the game, better it wasn't added at all tbh.

**Comment by DexterHaslem** [comment]
I actually cant reproduce it at all. @doublah if you can , delete discord-rpc.dll next to hl2 and see if it changes anything

**Comment by squeek502** [comment]
It's 100% reproducible for me. Renaming `discord-rpc.dll` so it doesn't load fixes it, and allowing it to load causes hl2.exe to hang after exit every time.

**Comment by DexterHaslem** [comment]
OK thanks! Will just push a rename to steam 


On Sat, Feb 17, 2018, at 04:16, Ryan Liptak wrote:
> It's 100% reproducible for me. Renaming discord-rpc.dll so it doesn't
> load fixes it, and allowing it to load causes hl2.exe to hang after
> exit every time.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 

--
  Dexter Haslem
  dmh@fastmail.com


Links:

  1. https://github.com/fortressforever/fortressforever/issues/351#issuecomment-366415148

**Comment by DexterHaslem** [comment]
'fixed' for now via steam build 2534841

**Comment by doublah** [comment]
May still be an issue, seen it happen a few times since the patch but not consistantly. Will do more testing.
