### ISSUE TITLE
Disable hud_keystate when in spectator freecam

### ISSUE THREAD

**Issue by doublah** [fortressforever/fortressforever#352]
Currently the key display is temporarily disabled if the person you're spectating dies, but it isn't really necessary or useful for spectator freecam, so it should be disabled there.

**Comment by squeek502** [comment]
I thought `hud_keystate_spec` already works like this. What's your `hud_keystate` setting?

**Comment by doublah** [comment]
Appears you were right, I still see no need for it in spec freecam but i'll change it to hud_keystate.

Sidenote: If we had auto spectator config exec as suggested in #295 this wouldn't be necessary :p

**Comment by squeek502** [comment]
Yeah, I'm not sure there's any real use-case for keystate ever being shown in freecam.
