### ISSUE TITLE
Visual C++ 2005 Express downloads are gone

### ISSUE THREAD

**Issue by squeek502** [fortressforever/fortressforever#386]
Links in the readme for Visual C++ 2005 Express are broken, need to either re-host them somewhere or find alternate downloads.

EDIT: Some potential:

- http://apdubey.blogspot.com/2009/04/microsoft-visual-studio-2005-express.html
- https://virtuallyfun.com/wordpress/2014/03/21/visual-studio-2005-express-editions/

**Comment by etkramer** [comment]
A potential, albiet difficult solution would be to port the game to SDK 2013 - in addition to not requiring an ancient IDE, it would also have the added benefit of supporting newer features such as borderless windows and custom shaders.
