### ISSUE TITLE
Reduce vertical grab bounds of the flag

### ISSUE THREAD

**Issue by mikeparker** [fortressforever/fortressforever#40]
I remember discussing this loads in the past. FF has a much taller flag than TFC basically, which means it's much easier to conc in, grab the flag and fly straight out again. It's easier to homerun, and it requires demos to det earlier as players fall onto the flag. TFC nearly requires you to be on the floor

I have a lua change which I'd like to put in, so :+1: me if this is OK, i've changed

```
 maxs.z = maxs.z / 2
```

to

```
 maxs.z = maxs.z / 3
```

which reduces the flag height by 33%, making it much more similar to TFC and requiring players to be closer to the ground when they grab flags.

**Comment by squeek502** [comment]
The current base_teamplay.lua in the beta branch actually already has significantly reduced flag bounds. See [svn r14557](http://forums.fortress-forever.com/showpost.php?p=502749&postcount=548)

> Modified base lua's to alter flag sizes for testing. All non-flags are unaffected.
> - Flag touch size is much smaller (cut in half, basically)
> - Flag collision size is smaller (width is cut in half, still only 1 unit high)

**Comment by mikeparker** [comment]
I thought the width felt a little low actually, that explains it! I think when we did testing with pure bounds before we didnt want to reduce the width and height equally. I'll double check all sizes.

**Comment by mikeparker** [comment]
What was the thinking behind reducing the width as well? Are you still keen on that?

**Comment by mikeparker** [comment]
After some more testing I'm fine with how it currently is. Closing
