### ISSUE TITLE
Disconnect: This Steam account does not own this game. 

### ISSUE THREAD

**Issue by squeek502** [fortressforever/fortressforever#45]
Figured I should create an issue for this. When connecting to a dedicated server, I get the following error:

```
Connecting to 64.74.97.32:27052...
Connected to 64.74.97.32:27052
Disconnect: This Steam account does not own this game. 
Please login to the correct Steam account.
```

No clue what to do. Will try to contact a Neotokyo dev or something. If you guys want to try it, just enter
`connect 64.74.97.32:27052` in the console.

**Comment by squeek502** [comment]
Neotokyo's dedicated server package has a different `bin/dedicated.dll`, which, if I try to use for FF, causes srcds.exe not to load at all. The other .dll files that differ don't seem to make a difference (`steamclient.dll`, `tier0_s.dll`, `vstdlib_s.dll`, and `bin/engine.dll`). Still fails to load if I use all of Neotokyo's SDK binaries.

**Comment by squeek502** [comment]
If I drop the FortressForever folder into the Neotokyo dedicated server package, I can load srcds and choose Fortress Forever and start a server, but I still get the "you don't own this game" error when I try to connect to it.

**Comment by hlstriker** [comment]
Just letting you know I get the same error. Is the dedicated server using a different appid than the client?

**Comment by squeek502** [comment]
After talking to a Neotokyo dev, he told me that [ChrisK](http://steamcommunity.com/id/FireSlash) and [psychonic](http://steamcommunity.com/id/psychonic) were the ones that helped them get Neotokyo working on Steam.

```
[13:16] <pushBAKw> are you working with chrisK over at valve?
[13:16] <pushBAKw> cause the two dudes that made it all possible were chrisK and psychonic
[13:16] <pushBAKw> without them we were dead in the water
[13:18] <pushBAKw> yeah.. chrisK is a valve employee for greenlight and he was STUNNED that psychonic figured it out
[13:19] <pushBAKw> dudes at valve coudnt even do it
```
