### ISSUE TITLE
Turn AvD objective icon off when flag is carried (for defenders, at least)

### ISSUE THREAD

**Issue by mikeparker** [fortressforever/fortressforever#58]
Currently the objective icon shows for defense players even when the flag is being carried, allows you to prefire on enemy offense. 

This is something that puts off new players, with a "wallhacking" style of play, and it makes it even harder to legitimately walk the flag towards the CP and encourages the one-off jump-to-CP play which kind of skips a lot of the fun of AvD.

Apparently this has been mentioned as an offputting mechanic a number of times on motos pub server.

I think although this does slightly weaken defense, we can come up with some other fixes to offset it.

**Comment by Largos** [comment]
Yes please.  This LOWERS the skill ceiling for Offense AND Defense and makes tricky paths (Dustbowl downstairs, Cornfield back route) almost useless.  

I don't see any newbies OR veterans liking this or benefiting from it.  Removal would be welcomed by all.

**Comment by alaswell** [comment]
So the two changes above will fix this for the base_id and base_ad files, it forces the defender's to always point at the current cap and never to the flag. This will fix most of the maps.

However, there are still a couple maps (Palermo/Cornfield) that are currently using the base_id_new file, and that file needs to be fixed anyway #60. So I didn't change it yet.

**Comment by alaswell** [comment]
I was thinking that it might be good/better if the flag became the defender's icon if/when it is dropped or tossed. That would kinda help balance the where the heck is the flag problem that this "fix" creates. But I see that being kinda annoying too, and if it changes too much then it's going to just be confusing and not helpful at all. IDK, maybe the new flag trails #46 will balance this enough that it won't be an issue??

**Comment by squeek502** [comment]
Done by fortressforever/fortressforever-scripts#13 and fortressforever/fortressforever-scripts#14

**Comment by fpsmoto** [comment]
Currently when flag is dropped on an AVD map, the defender icon appears at the command point being defended. The icon should be on the flag itself. If picked up by the enemy, then the icon should go to the CP being defended or have 2 separate icons, one always on the CP you are defending and another on the flag when it is dropped or at it's origin.
