### ISSUE TITLE
Remove excess maps from the default installation

### ISSUE THREAD

**Issue by mikeparker** [fortressforever/fortressforever#6]
We probably have a bunch of maps that we'd really rather people didn't play by default, and it bloats the installation a lot. 

Most games release with 6-10 maps so players aren't overwhelmed, and they can focus players towards the really good maps for a good initial play experience.

**Comment by AdamWillden** [comment]
Similarly to this if we decide on the '6-10' we should consider whether there are any modifications to LUA or BSP that should be made.

**Comment by mikeparker** [comment]
From the looks of my latest install, the currently shipped list is
- ff_bases (63 MB)
- ff_anticitizen (58 MB)
- ff_monkey (49 MB)
- ff_hunted (47 MB)
- ff_dustbowl (46 MB)
- ff_training (43 MB)
- ff_palermo (43 MB)
- ff_warpath (42 MB)
- ff_napoli (40 MB)
- ff_cz2 (34 MB)
- ff_crossover (33 MB)
- ff_aardvark (32 MB)
- ff_ksour (30 MB)
- ff_pitfall (27 MB)
- ff_shutdown2 (27 MB)
- ff_2fort (25 MB)
- ff_tiger (24 MB)
- ff_well (22 MB)
- ff_2morforever (21 MB)
- ff_schtop (19 MB)
- ff_dropdown (19 MB)
- ff_impact (18 MB)
- ff_roasted (15 MB)
- ff_genesis (14 MB)
- ff_openfire (14 MB)
- ff_cornfield (13 MB)
- ff_destroy (13 MB)
- ff_push (13 MB)
- ff_fusion (12 MB)
- ff_vertigo (8 MB)
- ff_epicenter (6 MB)
- ff_attrition (5 MB)
- ff_waterpolo (3 MB)
- ff_dm (1 MB)

**Comment by mikeparker** [comment]
Another thing to say is that we can include small / niche maps like ff_dm but leave them off the default maplist.

**Comment by mikeparker** [comment]
Here's my first stab, let me know what people think

**Default install:**

| CTF | AvD | ADZone | Misc |
| --- | --- | --- | --- |
| ff_aardvark (32 MB) | ff_ksour (30 MB) | ff_genesis (14 MB) | ff_training (43 MB) |
| ff_destroy (13 MB) | ff_dustbowl (46 MB) | ff_fusion (12 MB) | ff_dm (1 MB) |
| ff_monkey (49 MB) | ff_warpath (42 MB) |  | ff_waterpolo (3 MB) |
| ff_schtop (19 MB) | ff_napoli (40 MB) |  | :arrow_down: ff_push (13 MB) |
| ff_openfire (14 MB) |  |  |  |
| ff_shutdown2 (27 MB) |  |  |  |
| ff_2fort (25 MB) |  |  |  |
| :arrow_down: ff_well (22 MB) |  |  |  |
| :arrow_down: ff_roasted (15 MB) |  |  |  |

**_TOTAL: 460 MB**_

**Additional map pack:**

| CTF | AvD | ADZone | Misc |
| --- | --- | --- | --- |
| :arrow_up: ff_bases (63 MB) | ff_palermo (43 MB) | ff_impact (18 MB) | :arrow_up: ff_hunted (47 MB) |
| ff_crossover (33 MB) | ff_vertigo (8 MB) |  | :arrow_up: ff_cz2 (34 MB) |
| ff_pitfall (27 MB) | ff_cornfield (13 MB) |  | ff_tiger (24 MB) |
| ff_2morforever (21 MB) | ff_anticitizen (58 MB) |  | ff_epicenter (6 MB) |
| ff_dropdown (19 MB) |  |  | ff_attrition (5 MB) |

**_TOTAL: 419 MB**_

**Comment by AdamWillden** [comment]
Putting ff_well on that list alarms me a bit - since when has that ever worked in any capacity? I know it's a traditional map but it's one with a lot of problems. 

I think we could afford to lose a few more yet when I try and think about which should go I equally think of reasons they should stay! Except ff_well.

I wish compiling HDR didn't double the map size - can see which ones that has affected. Besides the point here I guess.

**Comment by hlstriker** [comment]
I feel the following should be added to the map pack:
ff_well
ff_genesis
ff_fusion
ff_push

I also feel the following should be added to the default install:
ff_bases
ff_cornfield

The most played maps should be on the default install and the least in the map pack.

Also, we should change the prefix of maps. ff_ is too generic. It should be ctf_, avd_, etc. This will really help new players select a map in public server votes.

As a side note, if the prefix is changed we will need to talk to the main server operators and ask them to change the prefix on the custom maps before the steam version is launched.

**Comment by hlstriker** [comment]
Just a thought but are any of the community maps worthy of being on the default installation? If so we should get permission from the mapper on adding it.

**Comment by mikeparker** [comment]
Yeah, ff_well is not a competitive map, but it was traditionally a fun map for 18v18 CTF pub mess-around. I guess if there are fun CTF pub maps that also work in competitive setting they are better, though.

**Comment by hlstriker** [comment]
The problem with the FF version of well is it's way too cramped for the games movement. It's just a cluster fuck where you're always bumping into stuff.

**Comment by squeek502** [comment]
- I think losing ff_palermo as a default would be unfortunate in the long run as it's a good map. Perhaps it can be removed from the initial release and then re-added in the beta while we iron out it's new scoring system a bit more, as that never really got the attention it deserved
- I'd be fine with dropping ff_pitfall from the default install and the map pack; it's kind of a garbage map that I'd need to remake from scratch to truly fix (not really suitable for pub or competitive play in its current state)
- I don't know that I can defend ff_hunted as a default map in terms of it being popular, but it really is a good, fun, unique, and iconic map. I've said it before and I'll say it again: the rounds of ff_hunted in the 2.1 beta was probably the most fun I've ever had playing FF.
- ff_cz2 is on par with ff_warpath, and potentially deserves a second look
- I'd consider dropping ff_roasted from the default, as it's a fairly niche competitive map and I can't imagine it plays well in pubs (perhaps [ff_stowaway](http://forums.fortress-forever.com/showthread.php?t=21165) would fit better? it was made by the same person)

**Comment by mikeparker** [comment]
I'd be happy including ff_hunted if we took out spies. I used to really enjoy it playing vs snipers, but it's not nearly as fun now you can get stabbed by an invisible player, or someone disguised as a teammate etc.

**Comment by mikeparker** [comment]
I'd be interested in more people's opinions on:
- Fusion
- Genesis
- Cornfield
- Push
- cz2

Out of curiosity, did we ever change cz2 so it's more fun with low player numbers? e.g. locking down points 1 and 5 or something. Also, is it still really slow whilst you're carrying a flag?

**Comment by squeek502** [comment]
Hunted has a 1 spy limit if I remember right. We could make that slot only open up past a certain number of players, perhaps. I thought that the spy really improved things when we played it in the 2.1 beta, but I can see how it can ruin things with small numbers of players.
- cz2 no longer has flags, and it hasn't for a long time. It uses the same system that warpath uses (which was originally written for cz2).
- cornfield feels too segmented and cramped for proper flow. It always feels really uneven (a round either goes really fast or really slow)
- push I don't have many thoughts about, but it has barely been played in any context afaik
- fusion and genesis are tricky; I'm not sure they have received much pub play, but I think it's probably worth still including them

Also, ff_dm **really** needs an overhaul.

**Comment by mikeparker** [comment]
Now that you mention it, I did know that, about cz2. 

Whenever i've played hunted as spy, i've found it pretty easy to kill the civ, even against a good bodyguard team. After a few stabs the map quickly gets voted away.

The best hunted games I've had are when bodyguard teams are slowly taken out one by one until the civ is left alone and then he gets killed as he nears the finish. With the spy it encourages an "all or nothing" playstyle which doesn't lend itself to good feedback loops and can get demoralising quite quickly. The worst hunted games are the ones where out of nowhere suddenly the civ is dead.

Also, having to shoot your teammates all the time isn't fun.

The other thing about the spy is it makes low player number games feel much more empty. If the spy is playing "stealth mode". If we didn't remove the spy altogether I guess I would vote for the spy slot opening up at higher player numbers, that would definitely help.

**Comment by mikeparker** [comment]
Have added up/down arrows for potentially what should be promoted/demoted

**Comment by alaswell** [comment]
I like it with the changes (arrows) that you have.

**Comment by AdamWillden** [comment]
Same. Also I agree we shouldn't push out ffdm as it is and it's shameful we've left it this long lol. Perhaps that's an easy one for the community to do?? Competition and vote for inclusion in steam release? Just got to look decent and function!

**Comment by squeek502** [comment]
In my opinion, ff_dm should be way more than a simple arena; it should be a showcase of what Lua is capable of. Automated mulch matches, smart spawning, multiple arenas, configurable DM modes per-arena, etc. It should be an all-in-one DM experience, not a tiny square box.

The fact that exo's mulch_dm port is 10x better than ff_dm is rather ridiculous.

**Comment by mikeparker** [comment]
Have opened a separate issue to revamp ff_dm -> https://github.com/fortressforever/fortressforever/issues/13

It seems like we should still include it though for now, it's good at what it's for, without a replacement?

**Comment by mikeparker** [comment]
I've removed some maps, I've not delete the following yet: ff_well, ff_bases, ff_palermo, ff_push

**Default install:**

| CTF | AvD | ADZone | Misc |
| --- | --- | --- | --- |
| ff_aardvark (32 MB) | ff_ksour (30 MB) | ff_genesis (14 MB) | ff_training (43 MB) |
| ff_destroy (13 MB) | ff_dustbowl (46 MB) | ff_fusion (12 MB) | ff_dm (1 MB) |
| ff_monkey (49 MB) | ff_warpath (42 MB) | :arrow_down:ff_impact (18 MB) | ff_waterpolo (3 MB) |
| ff_schtop (19 MB) | ff_napoli (40 MB) |  | ff_hunted (47 MB) |
| ff_openfire (14 MB) | :question:ff_palermo (43 MB) |  | ff_cz2 (34 MB) |
| ff_shutdown2 (27 MB) | :arrow_down:ff_vertigo (8 MB) |  | :question:ff_push (13 MB) |
| ff_2fort (25 MB) | :arrow_down:ff_cornfield (13 MB) |  | :arrow_down:ff_tiger (24 MB) |
| :question: ff_well (22 MB) | :arrow_down:ff_anticitizen (58 MB) |  | :arrow_down:ff_epicenter (6 MB) |
| :question: ff_bases (63 MB) |  |  | :arrow_down:ff_attrition (5 MB) |
| :arrow_down:ff_crossover (33 MB) |  |  |  |
| :arrow_down:ff_pitfall (27 MB) |  |  |  |
| :arrow_down:ff_2morforever (21 MB) |  |  |  |
| :arrow_down: ff_dropdown (19 MB) |  |  |  |

**_TOTAL SAVING: 232 MB**_

**Comment by squeek502** [comment]
- [cake lobbying for cornfield](http://forums.fortress-forever.com/showpost.php?p=504540&postcount=567)
- [KubeDawg lobbying for dropdown](http://forums.fortress-forever.com/showpost.php?p=504541&postcount=568)

EDIT: [Created a thread on the beta forums so that we can get some more feedback](http://forums.fortress-forever.com/showthread.php?t=24489)

**Comment by AfterShockFF** [comment]
What else needs doing here?

**Comment by squeek502** [comment]
I think dropping push and re-adding cornfield might be a good thing.

**Comment by TYRANNOSAURUSCOW** [comment]
From Mike's 25th October post above I would...

Drop:
- all with :arrow_down: or :question: except probably (but I don't feel strongly either way on it) palermo
- aardvark
- hunted
- cz2

Probably drop:
- waterpolo

Unless new players really prefer them over CTF/AvD (I'm not in a position to know), drop:
- fusion
- genesis

A few maps you like, ideally covering a couple of gamemodes, is all it takes to get into a multiplayer game.  Clearly maps you don't like may stop you from hanging around long enough to ever experience the maps you might have liked, or will just put you off the game if you do hang around long enough to know you like X/Y/Z but have to wait ages to play them.  I would therefore start minimalist (it's always easy to add more maps later) with the maps that are most likely to be enjoyed by everyone (even if that means putting some of the more subjective personal favourite "marmite" maps to one side for now).

Even with the fairly severe cutting suggestions I made above imo there are more than enough maps included for anyone who's ever likely to get into FF to do so (6 CTF, 5 AvD, 1 training, 1 dm) whilst keeping to a minimum the expected number of "marmite" maps.

I'm also strongly in favour of renaming maps so the gamemode is clear from the name (e.g. "ctf_2fort").

**Comment by AfterShockFF** [comment]
We did enough here to close for now
