### ISSUE TITLE
Allow Lua to spawn entities

### ISSUE THREAD

**Issue by squeek502** [fortressforever/fortressforever#63]
Can be done in Hammer using https://developer.valvesoftware.com/wiki/Env_entity_maker, but it'd be nice to be able to do it map-agnostically.

> 7:48 PM - squeek.: what were you intending to spawn?
> 7:49 PM - ルーキー: i havent really thought of it yet
> 7:49 PM - ルーキー: but it would be really useful
> 7:49 PM - ルーキー: lol
> 7:49 PM - ルーキー: being able to spawn flags at some points or anything else really
> 7:50 PM - ルーキー: just spawn new things when someone dies
> 7:50 PM - squeek.: you can use env_entity_maker to do that
> 7:50 PM - squeek.: and OutputEvent
> 7:50 PM - squeek.: to trigger it through lua
> 7:50 PM - ルーキー: what if it isnt in a map but
> 7:50 PM - ルーキー: ive been more modding other maps
> 7:50 PM - squeek.: right
> 7:50 PM - ルーキー: to use with ff as a whole

**Comment by R00Ki3** [comment]
Looking up how to use the entity_maker it seems that the point_template actually copies an entity to be spawned. So here's some more information on it. [https://developer.valvesoftware.com/wiki/Point_template](https://developer.valvesoftware.com/wiki/Point_template)
