### ISSUE TITLE
Add cl_adjustgrenadetimer console command to slightly delay the start of the grenade beeps

### ISSUE THREAD

**Issue by mikeparker** [fortressforever/fortressforever#8]
This is useful for TFC players who are used to a 50-100ms delay on the start of the grenade timer. 

Unsure how easy this is, theres a few options to achieveing this:
1. Just edit the sound file somehow, or output a custom sound file with x milliseconds of silence on the front, and trigger that
2. Use a built in method of triggering a sound after a certain delay, i'm unsure whether the source sdk has overloads that include delay - if so, this should be easy
3. Use some sort of background timer or something to trigger the sound at a later stage

**Comment by hlstriker** [comment]
Adding a feature like this is just a waste of time. Client side beeps are by far better for concing and these players are being entirely too picky. It will take them all but a week of concing to get used to client side beeps compared to networked beeps. The rest of us did it just fine.

**Comment by mikeparker** [comment]
Mentioned here http://forums.fortress-forever.com/showpost.php?p=504475&postcount=23

And i'm sure i've had other people ask me for it in the past too

**Comment by mikeparker** [comment]
I've looked into doing this quickly / easily, I can't see an easy way of doing it. There doesn't seem to be any overrides for EmitSound which take a delay before starting. I think to do it we'd either need to:

a) Start a background thread to start a timer then emit the sound then quit
b) Store the pending timer start times as a list on the client then check every tick when we should start one, and start it. I don't know if the exact timing of this would depend on the frame rate, though

I'm welcome to hear other suggestions.

**Comment by squeek502** [comment]
Ask the people suggesting this to stop being weirdos? :innocent:

This whole thing honestly confuses me. Can this not be "solved" by a custom timer on their end?

**Comment by mikeparker** [comment]
Yeah, they can just insert x milliseconds into their timer.wav, that's probably the easiest method tbh!

**Comment by mikeparker** [comment]
I've made a few custom timers very easily, 50ms, 75ms, 100ms, 125ms and 150ms delay. I'll put them on the forums
