### ISSUE TITLE
Get rid of single shotgun on as many classes as possible

### ISSUE THREAD

**Issue by squeek502** [fortressforever/fortressforever#82]
In light of [this video](https://www.youtube.com/watch?v=b8r5gRpsZLI) and others like it, the single shotgun is a huge point of confusion for new players. Having useless/redundant weapons makes no sense, so we should really start removing the clutter wherever it won't impact things too much.

Classes that should definitely have the single shotgun removed:
- Medic
- HWGuy
- Pyro

Classes that should maybe have the single shotgun removed:
- Soldier
- Scout

Classes that should definitely keep the single shotgun:
- Demoman

**Comment by Xylemon** [comment]
I don't mind the others loosing Single Shotgun, but I think scout should keep it. His arsenal feels completely fine to me.

**Comment by squeek502** [comment]
Yeah, it's more of a systemic problem with the scout; if he has any weapons at all, people are naturally going to assume that those weapons would have at least _some_ legitimate killing ability. Very, very few people are used to the idea that a class could exist without the ability to kill other players, and we currently do a pretty bad job of communicating that.

That's a separate issue, though.

**Comment by mikeparker** [comment]
Is it also the case that other games have the best weapons in low-numbered slots (1 is the best) and we have high slots as the best?

**Comment by ddm999** [comment]
Well I believe the whole low number = good weapon thing comes from the fact you have a small array of weapons.

Therefore, 1 is your primary weapon (generally your best), 2 is your secondary and 3 is a tertiary weapon. I wouldn't say that really applies to FF, with every class having 3-5 weapons. I don't feel changing the order would really change a new player's experience either.

I do approve of making each class only have 1 shotgun at most (gets rid of the whole "hurr durr in ff theres a thousand shotguns") though.

**Comment by Largos** [comment]
Agreed with only 1 shotgun on each class.  HWGuy in fact especially shouldn't have a single shotty, further cementing his role as up close and personal.  And medics hardly ever use the single shotty so it seems superfluous and just confusing to new people.

We could break every class down to "Primary, Secondary, Tertiary/Melee"

Scout - Nail, shotty, crowbar
Sniper - Sniper, AR, crowbar (nailgun seems totally worthless on sniper too)
Soldier - RPG, Shotgun, melee
Demo - Exception.  Two slots for two types of pipes, then shotgun, then crowbar, then detpack
HWGuy - AC, shotgun, melee
Medic - Supernail, shotgun, medkit
Spy - tranq, shotgun, knife
Engie - Rail, shotgun, wrench

The strange slots is a holdover from HL1 where Gordon carried a whole arsenal that was split up by category.  Since rockets came late in the game, it was slot5.

Kind of vestigial at this point, I like dropping extra shotguns and changing slots.  (Would make weapon configs more intuitive as well.)

I say keep it on the scout.  If he and the demo are the only classes with the shotgun then it's slightly clearer that this shotgun doesn't pack as much punch as other classes.

**Comment by DarthMan** [comment]
Add teleporters for enginners before the game gets released on Steam (maybe choose between building a jump pad as a scout or a tele as an engi , depending on the map).For example tele is very usesfull on dustbowl , but but not on maps like xpress :) , warpath etc

**Comment by squeek502** [comment]
@the-cake

> But yea, removing the little sg and reordering the weapons will slightly increase this game's appeal to the current audience.

I'm pretty sure there's a saying about rearranging deck chairs that fully vindicates this course of action.

I totally get where you're coming from. And for Soldier, I think I agree (hence why that pull request hasn't been merged, and may never be). However, I really don't think there's any reasonable amount of depth gained with the medic/hwguy having a single shotgun, and the pyro having it is largely irrelevant (it's only useful in pyro vs pyro, but even then it's insanely weak).

**Comment by Xylemon** [comment]
@DarthMan As much as I would love tele's in FF, I'm sure they'll never get added (even if completely optional to enable). You'd have better luck requesting that in a separate issue though, talking about it here won't do any good seeing as this is related to the Single Shotty.

**Comment by bigoj** [comment]
many of the best scouts i see in ff peck at the enemy on their runs in different ways with the nailgun and super shotty for longer range...it is mildly effective at wearing down d for the meds....

for example when a flag is in the yard and a soldier is low on health and rocket jumping after you or yard d with low health... its useful to have the single shotty as scout  bc the nails are easier to dodge and avoid, i also use the single shotty in emergencies when one last quickshot is necessary to kill an enemy at a longer range than nails would call for...I am for the scout and med keeping it mainly....the hw i could live without.... 

on monkey in a pickup a while back i can think of an instance where i killed u squeek as med when u were demo with single shotty as last hope after my super shotty ran out.. It made me question whether i really wanted it to go....

**Comment by squeek502** [comment]
Done for now. Soldier, scout, and demo will keep the single shotgun.

**Comment by Xylemon** [comment]
After playing 2fort with a friend, I noticed pyro is kinda useless underwater and without the single shotty has no form of defense. Was this intentional?

**Comment by GIMP-Nutter** [comment]
What Xylemon said. It also stands that the single shotgun is Pyro's only hitscan weapon, meaning without it, he's not an effective class for players who suck at prediction.

**Comment by FDA-** [comment]
Pyros of all skill levels in tf2 give up their hitscan in favor of a flame projectile that is all around worse than the IC cannon. Tbh I think it's fine, the pyro is a cqc class and has good tools for closing in on his targets.

**Comment by GIMP-Nutter** [comment]
The "underwater" point still stands.

**Comment by squeek502** [comment]
This is relevant: https://github.com/fortressforever/fortressforever/issues/149
More discussion: http://forums.fortress-forever.com/showthread.php?t=25037
