### ISSUE TITLE
Duplicate Timer Sounds

### ISSUE THREAD

**Issue by Xylemon** [fortressforever/fortressforever#83]
For some reason there seems to be two "White unicorn" sound files, one being more high quality than the other, and there's two "mulchtimer" sounds that seem to be exactly the same. Also does having no sound have to be a sound? Couldn't it just not play anything when the player selects the option to not play a sound?

**Comment by AdamWillden** [comment]
I remember sorting the sounds out a fair while ago. If i remember correctly only certain sound files with certain bit rates and sampling rates would actually work. 

I don't know why I would have kept any duplicates though...

**Comment by squeek502** [comment]
Looks like they got re-added when the beta branch split from dev (using a clean 2.45 install, which had both timers, presumably due to the purely additive nature of patches and me messing up somewhere along the line).

Deleted the duplicates.
