### ISSUE TITLE
Pain sounds cover up other sounds

### ISSUE THREAD

**Issue by Xylemon** [fortressforever/fortressforever#84]
From what I understand, things like initial infection from another medic are supposed to play a sound like unclean1.wav, but they are covered up by pain sounds as pointed out by someone in beta testing today.

**Comment by squeek502** [comment]
This doesn't seem to be the case (the unclean.wav trying to get played part; feel free to open a new issue if pain sounds are an issue in other places). The only place "infected.saveme" is emitted is from a player manually using the "saveme" command.

https://github.com/fortressforever/fortressforever/blob/beta/game_shared/ff/ff_player_shared.cpp#L1781

**Comment by Xylemon** [comment]
Ah I see, thanks for the info.
