### ISSUE TITLE
With require() replacing IncludeScript(), included files are not logged.

### ISSUE THREAD

**Issue by ddm999** [fortressforever/fortressforever#92]
Included scripts are no longer logged as being loaded at all in console.

(Also I hit enter before I was done. :P So good at using GitHub.)

**Comment by squeek502** [comment]
Could you explain why this functionality was desirable? I intentionally left it out. Note that failing to find a require'd module will result in an error.

**Comment by ddm999** [comment]
It's helpful to know what's been loaded and what hasn't. For instance, if you're setting up a new include in a globalscript. (I actually thought my server.cfg was wrong or something when I didn't see the base_friendlyfire.lua include in console.)

If you're removing it then that's fair enough, but then surely the base.lua loading shouldn't be shown either? I mean that's less important to know (given it loads every time) than the includes anyway.

**Comment by squeek502** [comment]
base.lua is automatically loaded every map via the same method as mapname.lua.

See: https://github.com/fortressforever/fortressforever/blob/beta/dlls/ff/ff_scriptman.cpp#L302-L347

So, making it clear that base.lua, mapname.lua, and sv_globalluascript lua are all loaded allows for some transparency, as they are the only true entry points to the Lua environment.

**Comment by ddm999** [comment]
Fair enough.

(Also I had no idea those were actually posted because the script behind GitHub doesn't work at all on consoles. :P)

Seen as it's intended rather than an actual issue I'll go and close this.
