### ISSUE TITLE
Modify the map guide options on team select.

### ISSUE THREAD

**Issue by ddm999** [fortressforever/fortressforever#94]
- Basically no maps in FF have an image for the map guides. Therefore, there should probably either be a default one if one isn't found, or it should be blank rather than being the black and purple missing texture checkerbox.
- Most maps don't even have map guides. It'd probably be better if the non-existent mapguides are greyed out and unselectable.
  - And if there are no map guides at all, I'd recommend having the "View Flythrough" option on the team select screen greyed out and unselectable.

**Comment by squeek502** [comment]
Makes sense.

**Comment by squeek502** [comment]
#97 does most of this. Greying out the flythrough button based on mapguide existence is a bit of a pain so I didn't end up doing that.
